//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Legis.Entity.Negocio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LegisEntities : DbContext
    {
        public LegisEntities()
            : base("name=LegisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Candidato> Candidato { get; set; }
        public virtual DbSet<CandidatoEleccion> CandidatoEleccion { get; set; }
        public virtual DbSet<Eleccion> Eleccion { get; set; }
        public virtual DbSet<Voto> Voto { get; set; }
        public virtual DbSet<Sufragante> Sufragante { get; set; }
    }
}
