//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Legis.Entity.Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voto
    {
        public int IdVoto { get; set; }
        public int IdEleccion { get; set; }
        public int IdSufragante { get; set; }
    
        public virtual Eleccion Eleccion { get; set; }
        public virtual Sufragante Sufragante { get; set; }
    }
}
